# Generated by Django 2.2.13 on 2020-08-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateCompleted', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(default=False)),
                ('avatar', models.ImageField(upload_to='projects/images')),
            ],
        ),
    ]
